/****** COPYRIGHT JINAN KORDAB 6.18.2020 ******/
/****** Script Date: 6/17/2020 6:03:19 PM ******/
/****** IT IS FORBIDDEN TO COPY OR USE THIS CODE WITHOUT THE WRITTEN PERMISSION OF AN AUTHOR , JINAN KORDAB ******/
/****** FOR INFORMATION OR CONTACT,PLEASE SEND AN EMAILTO KORDABJINAN@GMAIL.COM******/


USE [SCRUM]
GO

/****** Object:  Table [dbo].[PERSON]    Script Date: 6/17/2020 6:03:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERSON](
	[USERID] [bigint] IDENTITY(1,1) NOT NULL,
	[NICKNAME] [nvarchar](50) NOT NULL,
	[FIRSTNAME] [nvarchar](50) NOT NULL,
	[LASTNAME] [nvarchar](50) NOT NULL,
	[EMAIL] [nvarchar](max) NOT NULL,
	[REGISTRATIONDATE] [datetime] NOT NULL,
	[PROFILEPICTURE] [varbinary](max) NULL,
	[PASSWORD] [nvarchar](max) NULL,
	[PKEY] [varbinary](max) NULL,
	[PIV] [varbinary](max) NULL,
	[ISTEAMCREATOR] [bit] NOT NULL,
 CONSTRAINT [PK_PERSON] PRIMARY KEY CLUSTERED 
(
	[USERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


/*********************************/


USE [SCRUM]
GO

/****** Object:  Table [dbo].[PBATTACHMENT]    Script Date: 6/17/2020 6:03:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PBATTACHMENT](
	[PBATTITEMID] [bigint] IDENTITY(1,1) NOT NULL,
	[PBATTACHMENTNAME] [nvarchar](50) NOT NULL,
	[PBATTACHMENTTYPE] [nvarchar](50) NOT NULL,
	[PBATTACHMENTLENGTH] [bigint] NOT NULL,
	[PBATTACHMENTCONTENT] [varbinary](max) NOT NULL,
	[PBFKPRODUCTBACKLOG] [bigint] NOT NULL,
 CONSTRAINT [PK_PBATTACHMENT] PRIMARY KEY CLUSTERED 
(
	[PBATTITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


/***********************************/


USE [SCRUM]
GO

/****** Object:  Table [dbo].[ATTACHMENT]    Script Date: 6/17/2020 6:04:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ATTACHMENT](
	[ATTITEMID] [bigint] IDENTITY(1,1) NOT NULL,
	[ATTACHMENTNAME] [nvarchar](50) NOT NULL,
	[ATTACHMENTTYPE] [nvarchar](50) NOT NULL,
	[ATTACHMENTLENGTH] [bigint] NOT NULL,
	[ATTACHMENTCONTENT] [varbinary](max) NOT NULL,
	[FKITEMID] [bigint] NOT NULL,
 CONSTRAINT [PK_ATTACHMENT] PRIMARY KEY CLUSTERED 
(
	[ATTITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


/**************************************/


USE [SCRUM]
GO

/****** Object:  Table [dbo].[CLIENT]    Script Date: 6/17/2020 6:04:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENT](
	[CLIENTID] [bigint] IDENTITY(1,1) NOT NULL,
	[CLIENTNAME] [nvarchar](max) NOT NULL,
	[CLIENTLOCATION] [nvarchar](max) NULL,
	[CLIENTDESCRIPTION] [nvarchar](max) NULL,
	[CLIENTPHONENUMBER] [nvarchar](50) NULL,
	[ATTACHMENTSCOUNT] [int] NOT NULL,
	[FKPERSONID] [bigint] NULL,
 CONSTRAINT [PK_CLIENT] PRIMARY KEY CLUSTERED 
(
	[CLIENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLIENT]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_CLIENT] FOREIGN KEY([CLIENTID])
REFERENCES [dbo].[CLIENT] ([CLIENTID])
GO

ALTER TABLE [dbo].[CLIENT] CHECK CONSTRAINT [FK_CLIENT_CLIENT]
GO


/********************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[EPIC]    Script Date: 6/17/2020 6:05:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EPIC](
	[EPICID] [bigint] IDENTITY(1,1) NOT NULL,
	[EPICTITLE] [nvarchar](50) NOT NULL,
	[EPICDESCRIPTION] [nvarchar](max) NULL,
	[FKCLIENTID] [bigint] NOT NULL,
 CONSTRAINT [PK_EPIC] PRIMARY KEY CLUSTERED 
(
	[EPICID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[EPIC]  WITH CHECK ADD  CONSTRAINT [FK_EPIC_CLIENT] FOREIGN KEY([FKCLIENTID])
REFERENCES [dbo].[CLIENT] ([CLIENTID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[EPIC] CHECK CONSTRAINT [FK_EPIC_CLIENT]
GO


/***********************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[PRODUCTBACKLOG]    Script Date: 6/17/2020 6:05:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUCTBACKLOG](
	[ITEMID] [bigint] IDENTITY(1,1) NOT NULL,
	[ITEMTITLE] [nvarchar](23) NOT NULL,
	[CREATIONDATE] [datetime] NOT NULL,
	[ATTACHMENTSCOUNT] [int] NOT NULL,
	[LINKCOUNT] [int] NOT NULL,
	[ITEMNOTES] [nvarchar](max) NULL,
	[ITEMLOCATION] [nvarchar](10) NULL,
	[FKEPICID] [bigint] NOT NULL,
 CONSTRAINT [PK_PRODUCTBACKLOG] PRIMARY KEY CLUSTERED 
(
	[ITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUCTBACKLOG]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTBACKLOG_EPIC] FOREIGN KEY([FKEPICID])
REFERENCES [dbo].[EPIC] ([EPICID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PRODUCTBACKLOG] CHECK CONSTRAINT [FK_PRODUCTBACKLOG_EPIC]
GO


/*****************************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[PICTURE]    Script Date: 6/18/2020 3:47:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PICTURE](
	[PERSONPICTUREID] [bigint] IDENTITY(1,1) NOT NULL,
	[PERSONPICTURENAME] [nvarchar](50) NOT NULL,
	[PERSONPICTURETYPE] [nvarchar](50) NOT NULL,
	[PERSONPICTURELENGTH] [bigint] NOT NULL,
	[PERSONPICTURECONTENT] [varbinary](max) NOT NULL,
	[FKPERSONID] [bigint] NOT NULL,
 CONSTRAINT [PK_PICTURE] PRIMARY KEY CLUSTERED 
(
	[PERSONPICTUREID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PICTURE]  WITH CHECK ADD  CONSTRAINT [FK_PICTURE_PERSON] FOREIGN KEY([FKPERSONID])
REFERENCES [dbo].[PERSON] ([USERID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PICTURE] CHECK CONSTRAINT [FK_PICTURE_PERSON]
GO


/*******************************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[SPRINTARCHIVE]    Script Date: 6/18/2020 3:47:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SPRINTARCHIVE](
	[SPRINTARCHIVEID] [bigint] IDENTITY(1,1) NOT NULL,
	[SPRINTARCHIVESTARTDATE] [datetime] NOT NULL,
	[SPRINTARCHIVEENDDATE] [datetime] NOT NULL,
	[FKCLIENTID] [bigint] NOT NULL,
	[FKEPICID] [bigint] NOT NULL,
 CONSTRAINT [PK_SPRINTARCHIVE] PRIMARY KEY CLUSTERED 
(
	[SPRINTARCHIVEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SPRINTARCHIVE]  WITH CHECK ADD  CONSTRAINT [FK_SPRINTARCHIVE_CLIENT] FOREIGN KEY([FKCLIENTID])
REFERENCES [dbo].[CLIENT] ([CLIENTID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[SPRINTARCHIVE] CHECK CONSTRAINT [FK_SPRINTARCHIVE_CLIENT]
GO


/**************************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[TEAM]    Script Date: 6/18/2020 3:48:20 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TEAM](
	[TEAMID] [bigint] IDENTITY(1,1) NOT NULL,
	[TEAMNAME] [nvarchar](50) NOT NULL,
	[FKPERSONID] [bigint] NOT NULL,
 CONSTRAINT [PK_TEAM] PRIMARY KEY CLUSTERED 
(
	[TEAMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TEAM]  WITH CHECK ADD  CONSTRAINT [FK_TEAM_PERSON] FOREIGN KEY([FKPERSONID])
REFERENCES [dbo].[PERSON] ([USERID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TEAM] CHECK CONSTRAINT [FK_TEAM_PERSON]
GO


/*******************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[SPRINTARCHIVEBACKLOG]    Script Date: 6/18/2020 3:48:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SPRINTARCHIVEBACKLOG](
	[SPRINTARCHIVEBACKLOGID] [bigint] IDENTITY(1,1) NOT NULL,
	[FKSPRINTARCHIVE] [bigint] NOT NULL,
	[FKBACKLOGID] [bigint] NOT NULL,
	[FKBACKLOGEPICID] [bigint] NULL,
 CONSTRAINT [PK_SPRINTARCHIVEBACKLOG] PRIMARY KEY CLUSTERED 
(
	[SPRINTARCHIVEBACKLOGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SPRINTARCHIVEBACKLOG]  WITH CHECK ADD  CONSTRAINT [FK_SPRINTARCHIVEBACKLOG_SPRINTARCHIVE] FOREIGN KEY([FKSPRINTARCHIVE])
REFERENCES [dbo].[SPRINTARCHIVE] ([SPRINTARCHIVEID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[SPRINTARCHIVEBACKLOG] CHECK CONSTRAINT [FK_SPRINTARCHIVEBACKLOG_SPRINTARCHIVE]
GO


/***************************************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[PBHYPERLINK]    Script Date: 6/18/2020 3:49:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PBHYPERLINK](
	[PBLINKITEMID] [bigint] IDENTITY(1,1) NOT NULL,
	[PBLINKDESCRIPTION] [nvarchar](50) NOT NULL,
	[PBLINKBODY] [nvarchar](50) NOT NULL,
	[PBFKPBACKLOG] [bigint] NOT NULL,
 CONSTRAINT [PK_PBHYPERLINK] PRIMARY KEY CLUSTERED 
(
	[PBLINKITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PBHYPERLINK]  WITH CHECK ADD  CONSTRAINT [FK_PBHYPERLINK_PRODUCTBACKLOG] FOREIGN KEY([PBFKPBACKLOG])
REFERENCES [dbo].[PRODUCTBACKLOG] ([ITEMID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PBHYPERLINK] CHECK CONSTRAINT [FK_PBHYPERLINK_PRODUCTBACKLOG]
GO


/**************************************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[ITEM]    Script Date: 6/18/2020 3:49:46 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ITEM](
	[ITEMID] [bigint] IDENTITY(1,1) NOT NULL,
	[ITEMTITLE] [nvarchar](23) NOT NULL,
	[CREATIONDATE] [datetime] NOT NULL,
	[ATTACHMENTSCOUNT] [int] NOT NULL,
	[LINKCOUNT] [int] NOT NULL,
	[ITEMNOTES] [nvarchar](max) NULL,
	[ITEMLOCATION] [nvarchar](10) NULL,
	[FKPERSONID] [bigint] NOT NULL,
	[FKPRODUCTBACKLOGID] [bigint] NOT NULL,
 CONSTRAINT [PK_ITEM] PRIMARY KEY CLUSTERED 
(
	[ITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PERSON] FOREIGN KEY([FKPERSONID])
REFERENCES [dbo].[PERSON] ([USERID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ITEM] CHECK CONSTRAINT [FK_ITEM_PERSON]
GO

ALTER TABLE [dbo].[ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PRODUCTBACKLOG] FOREIGN KEY([FKPRODUCTBACKLOGID])
REFERENCES [dbo].[PRODUCTBACKLOG] ([ITEMID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ITEM] CHECK CONSTRAINT [FK_ITEM_PRODUCTBACKLOG]
GO

/*******************************************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[HYPERLINK]    Script Date: 6/18/2020 3:50:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HYPERLINK](
	[LINKITEMID] [bigint] IDENTITY(1,1) NOT NULL,
	[LINKDESCRIPTION] [nvarchar](50) NOT NULL,
	[LINKBODY] [nvarchar](50) NOT NULL,
	[FKITEMID] [bigint] NOT NULL,
 CONSTRAINT [PK_HYPERLINK] PRIMARY KEY CLUSTERED 
(
	[LINKITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HYPERLINK]  WITH CHECK ADD  CONSTRAINT [FK_HYPERLINK_ITEM] FOREIGN KEY([FKITEMID])
REFERENCES [dbo].[ITEM] ([ITEMID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[HYPERLINK] CHECK CONSTRAINT [FK_HYPERLINK_ITEM]
GO


/*****************************************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[CLIENTATTACHMENT]    Script Date: 6/18/2020 3:50:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTATTACHMENT](
	[CATTACHMENTID] [bigint] IDENTITY(1,1) NOT NULL,
	[CATTACHMENTNAME] [nvarchar](50) NOT NULL,
	[CATTACHMENTTYPE] [nvarchar](50) NOT NULL,
	[CATTACHMENTLENGTH] [bigint] NOT NULL,
	[CATTACHMENTCONTENT] [varbinary](max) NOT NULL,
	[FKCLIENTID] [bigint] NOT NULL,
 CONSTRAINT [PK_CLIENTATTACHMENT] PRIMARY KEY CLUSTERED 
(
	[CATTACHMENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLIENTATTACHMENT]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTATTACHMENT_CLIENT] FOREIGN KEY([FKCLIENTID])
REFERENCES [dbo].[CLIENT] ([CLIENTID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CLIENTATTACHMENT] CHECK CONSTRAINT [FK_CLIENTATTACHMENT_CLIENT]
GO



/*****************************************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[LOG]    Script Date: 6/23/2020 10:14:12 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOG](
	[LogId] [bigint] IDENTITY(1,1) NOT NULL,
	[CONTROLLER] [nvarchar](max) NOT NULL,
	[EXCEPTION] [nvarchar](max) NOT NULL,
	[STACKTRACE] [nvarchar](max) NOT NULL,
	[EXDATETIME] [datetime] NOT NULL,
	[USERID] [bigint] NOT NULL,
 CONSTRAINT [PK_LOG] PRIMARY KEY CLUSTERED 
(
	[LogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


/****************************************************************/

USE [SCRUM]
GO

/****** Object:  Table [dbo].[RequestStat]    Script Date: 6/30/2020 6:45:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RequestStat](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IP] [nvarchar](max) NULL,
	[browser] [nvarchar](max) NULL,
	[platform] [nvarchar](max) NULL,
	[ClientInnerWidth] [nvarchar](max) NULL,
	[ClientInnerHeight] [nvarchar](max) NULL,
	[ClientUserAgent] [nvarchar](max) NULL,
	[ClientScreenWidth] [nvarchar](max) NULL,
	[ClientScreenHeight] [nvarchar](max) NULL,
	[ClientScreenAvailableWidth] [nvarchar](max) NULL,
	[ClientSreenAvailableHeight] [nvarchar](max) NULL,
 CONSTRAINT [PK_RequestStat] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO





