//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACHMENT
    {
        public long ATTITEMID { get; set; }
        public string ATTACHMENTNAME { get; set; }
        public string ATTACHMENTTYPE { get; set; }
        public long ATTACHMENTLENGTH { get; set; }
        public byte[] ATTACHMENTCONTENT { get; set; }
        public long FKITEMID { get; set; }
    }
}
