//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.CLIENTATTACHMENTs = new HashSet<CLIENTATTACHMENT>();
            this.EPICs = new HashSet<EPIC>();
            this.SPRINTARCHIVEs = new HashSet<SPRINTARCHIVE>();
        }
    
        public long CLIENTID { get; set; }
        public string CLIENTNAME { get; set; }
        public string CLIENTLOCATION { get; set; }
        public string CLIENTDESCRIPTION { get; set; }
        public string CLIENTPHONENUMBER { get; set; }
        public int ATTACHMENTSCOUNT { get; set; }
        public Nullable<long> FKPERSONID { get; set; }
    
        public virtual CLIENT CLIENT1 { get; set; }
        public virtual CLIENT CLIENT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTATTACHMENT> CLIENTATTACHMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPIC> EPICs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPRINTARCHIVE> SPRINTARCHIVEs { get; set; }
    }
}
