//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTATTACHMENT
    {
        public long CATTACHMENTID { get; set; }
        public string CATTACHMENTNAME { get; set; }
        public string CATTACHMENTTYPE { get; set; }
        public long CATTACHMENTLENGTH { get; set; }
        public byte[] CATTACHMENTCONTENT { get; set; }
        public long FKCLIENTID { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
    }
}
