//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HYPERLINK
    {
        public long LINKITEMID { get; set; }
        public string LINKDESCRIPTION { get; set; }
        public string LINKBODY { get; set; }
        public long FKITEMID { get; set; }
    
        public virtual ITEM ITEM { get; set; }
    }
}
