//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.HYPERLINKs = new HashSet<HYPERLINK>();
        }
    
        public long ITEMID { get; set; }
        public string ITEMTITLE { get; set; }
        public System.DateTime CREATIONDATE { get; set; }
        public int ATTACHMENTSCOUNT { get; set; }
        public int LINKCOUNT { get; set; }
        public string ITEMNOTES { get; set; }
        public string ITEMLOCATION { get; set; }
        public long FKPERSONID { get; set; }
        public long FKPRODUCTBACKLOGID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HYPERLINK> HYPERLINKs { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual PRODUCTBACKLOG PRODUCTBACKLOG { get; set; }
    }
}
