//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBATTACHMENT
    {
        public long PBATTITEMID { get; set; }
        public string PBATTACHMENTNAME { get; set; }
        public string PBATTACHMENTTYPE { get; set; }
        public long PBATTACHMENTLENGTH { get; set; }
        public byte[] PBATTACHMENTCONTENT { get; set; }
        public long PBFKPRODUCTBACKLOG { get; set; }
    }
}
