//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBHYPERLINK
    {
        public long PBLINKITEMID { get; set; }
        public string PBLINKDESCRIPTION { get; set; }
        public string PBLINKBODY { get; set; }
        public long PBFKPBACKLOG { get; set; }
    
        public virtual PRODUCTBACKLOG PRODUCTBACKLOG { get; set; }
    }
}
