//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTBACKLOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTBACKLOG()
        {
            this.ITEMs = new HashSet<ITEM>();
            this.PBHYPERLINKs = new HashSet<PBHYPERLINK>();
        }
    
        public long ITEMID { get; set; }
        public string ITEMTITLE { get; set; }
        public System.DateTime CREATIONDATE { get; set; }
        public int ATTACHMENTSCOUNT { get; set; }
        public int LINKCOUNT { get; set; }
        public string ITEMNOTES { get; set; }
        public string ITEMLOCATION { get; set; }
        public long FKEPICID { get; set; }
    
        public virtual EPIC EPIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM> ITEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PBHYPERLINK> PBHYPERLINKs { get; set; }
    }
}
