//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStat
    {
        public long ID { get; set; }
        public string IP { get; set; }
        public string browser { get; set; }
        public string platform { get; set; }
        public string ClientInnerWidth { get; set; }
        public string ClientInnerHeight { get; set; }
        public string ClientUserAgent { get; set; }
        public string ClientScreenWidth { get; set; }
        public string ClientScreenHeight { get; set; }
        public string ClientScreenAvailableWidth { get; set; }
        public string ClientSreenAvailableHeight { get; set; }
    }
}
