//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCRUMEntities : DbContext
    {
        public SCRUMEntities()
            : base("name=SCRUMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATTACHMENT> ATTACHMENTs { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<CLIENTATTACHMENT> CLIENTATTACHMENTs { get; set; }
        public virtual DbSet<EPIC> EPICs { get; set; }
        public virtual DbSet<HYPERLINK> HYPERLINKs { get; set; }
        public virtual DbSet<ITEM> ITEMs { get; set; }
        public virtual DbSet<LOG> LOGs { get; set; }
        public virtual DbSet<PBATTACHMENT> PBATTACHMENTs { get; set; }
        public virtual DbSet<PBHYPERLINK> PBHYPERLINKs { get; set; }
        public virtual DbSet<PERSON> People { get; set; }
        public virtual DbSet<PICTURE> PICTUREs { get; set; }
        public virtual DbSet<PRODUCTBACKLOG> PRODUCTBACKLOGs { get; set; }
        public virtual DbSet<RequestStat> RequestStats { get; set; }
        public virtual DbSet<SPRINTARCHIVE> SPRINTARCHIVEs { get; set; }
        public virtual DbSet<SPRINTARCHIVEBACKLOG> SPRINTARCHIVEBACKLOGs { get; set; }
        public virtual DbSet<TEAM> TEAMs { get; set; }
    }
}
