//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRINTARCHIVEBACKLOG
    {
        public long SPRINTARCHIVEBACKLOGID { get; set; }
        public long FKSPRINTARCHIVE { get; set; }
        public long FKBACKLOGID { get; set; }
        public Nullable<long> FKBACKLOGEPICID { get; set; }
    
        public virtual SPRINTARCHIVE SPRINTARCHIVE { get; set; }
    }
}
