//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRINTARCHIVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPRINTARCHIVE()
        {
            this.SPRINTARCHIVEBACKLOGs = new HashSet<SPRINTARCHIVEBACKLOG>();
        }
    
        public long SPRINTARCHIVEID { get; set; }
        public System.DateTime SPRINTARCHIVESTARTDATE { get; set; }
        public System.DateTime SPRINTARCHIVEENDDATE { get; set; }
        public long FKCLIENTID { get; set; }
        public long FKEPICID { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPRINTARCHIVEBACKLOG> SPRINTARCHIVEBACKLOGs { get; set; }
    }
}
